[package]
name = "daemon"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "daemon"
path = "src/main.rs"

[dependencies]
shared = { path = "../shared" }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
zbus = { version = "5", features = ["tokio"] }
anyhow = "1"
mlua = { version = "0.10", features = ["lua54", "async", "send"] }
dirs = "6"
