#!/usr/bin/env python3
import evdev, time, sys

hold = float(sys.argv[1]) if len(sys.argv) > 1 else 4.0

cap = {evdev.ecodes.EV_KEY: [evdev.ecodes.KEY_POWER]}
ui = evdev.UInput(cap, name="Power Button", bustype=evdev.ecodes.BUS_HOST)
time.sleep(0.1)
ui.write(evdev.ecodes.EV_KEY, evdev.ecodes.KEY_POWER, 1)
ui.syn()
time.sleep(hold)
ui.write(evdev.ecodes.EV_KEY, evdev.ecodes.KEY_POWER, 0)
ui.syn()
time.sleep(0.1)
ui.close()
