buildscript {
	repositories {
		maven { url 'https://maven.fabricmc.net/' }
		maven { url 'https://maven.fabricmc.net/repository/fabric-snapshots' }
		mavenCentral()
		gradlePluginPortal()
	}
	dependencies {
		classpath "net.fabricmc:fabric-loom:${loom_version}"
	}
}

apply plugin: 'java'
apply plugin: 'net.fabricmc.loom'
apply plugin: 'maven-publish'

version = project.mod_version
group = project.maven_group

repositories {
	maven { url = 'https://maven.fabricmc.net/' }
	mavenCentral()
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"modid" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${minecraft_version}"
	mappings loom.layered {
		mappings "net.fabricmc:yarn:${yarn_mappings}:v2"
	}
	modImplementation "net.fabricmc:fabric-loader:${loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	inputs.property "projectName", project.name

	from("LICENSE") {
		rename { "${it}_${project.name}" }
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}
	repositories {}
}
