#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include "limine.h"
#include "gdt.h"
#include "idt.h"
#include "shell.h"

// --- Limine Base Revision & Requests ---
LIMINE_BASE_REVISION(2);

static volatile struct limine_framebuffer_request framebuffer_request = {
    .id = LIMINE_FRAMEBUFFER_REQUEST,
    .revision = 0
};

static volatile struct limine_hhdm_request hhdm_request = {
    .id = LIMINE_HHDM_REQUEST,
    .revision = 0
};

// --- PSF1 Font Structure ---
#define PSF1_MAGIC0 0x36
#define PSF1_MAGIC1 0x04

typedef struct {
    uint8_t magic[2];
    uint8_t mode;
    uint8_t charsize; // Font height in pixels (typically 16)
} __attribute__((packed)) psf1_header_t;

// Symbols generated by objcopy for font.o
extern char _binary_font_psf_start[];
extern char _binary_font_psf_end[];

// --- Framebuffer & Cursor State ---
static struct limine_framebuffer *fb = NULL;
static size_t cursor_x = 0;
static size_t cursor_y = 0;

// Draw a single character using font bitmask
void draw_char(char c, size_t cx, size_t cy, uint32_t fg_color, uint32_t bg_color) {
    psf1_header_t *font = (psf1_header_t *)_binary_font_psf_start;

    // Verify magic header
    if (font->magic[0] != PSF1_MAGIC0 || font->magic[1] != PSF1_MAGIC1) {
        return;
    }

    uint8_t *glyph_buffer = (uint8_t *)_binary_font_psf_start + sizeof(psf1_header_t);
    uint8_t *glyph = glyph_buffer + (c * font->charsize);
    volatile uint32_t *fb_ptr = (volatile uint32_t *)fb->address;
    size_t pitch_pixels = fb->pitch / 4;

    for (size_t y = 0; y < font->charsize; y++) {
        uint8_t row = glyph[y];
        for (size_t x = 0; x < 8; x++) {
            uint32_t color = (row & (0x80 >> x)) ? fg_color : bg_color;
            fb_ptr[(cy + y) * pitch_pixels + (cx + x)] = color;
        }
    }
}

// Print a string to the framebuffer with automatic wrap and newline handling
void kprint(const char *str, uint32_t fg_color, uint32_t bg_color) {
    psf1_header_t *font = (psf1_header_t *)_binary_font_psf_start;
    size_t font_height = font->charsize;

    for (size_t i = 0; str[i] != '\0'; i++) {
        if (str[i] == '\n') {
            cursor_x = 20;
            cursor_y += font_height;
            continue;
        }

        draw_char(str[i], cursor_x, cursor_y, fg_color, bg_color);
        cursor_x += 8;

        if (cursor_x + 8 >= fb->width) {
            cursor_x = 20;
            cursor_y += font_height;
        }
    }
}

// Clear the entire screen with a solid background color
void clear_screen(uint32_t color) {
    volatile uint32_t *fb_ptr = (volatile uint32_t *)fb->address;
    size_t total_pixels = (fb->pitch / 4) * fb->height;
    for (size_t i = 0; i < total_pixels; i++) {
        fb_ptr[i] = color;
    }
    // Reset cursor position to top-left margin
    cursor_x = 20;
    cursor_y = 20;
}

// Erase 1 character visually on backspace press
void draw_backspace(void) {
    if (cursor_x >= 28) { // Prevents backspacing past prompt left margin
        cursor_x -= 8;
        volatile uint32_t *fb_ptr = (volatile uint32_t *)fb->address;
        size_t pitch_pixels = fb->pitch / 4;

        for (size_t y = 0; y < 16; y++) {
            for (size_t x = 0; x < 8; x++) {
                fb_ptr[(cursor_y + y) * pitch_pixels + (cursor_x + x)] = 0x001A1C23;
            }
        }
    }
}

void _start(void) {
    // 1. Verify Limine revision compatibility
    if (LIMINE_BASE_REVISION_SUPPORTED == false) {
        while (1) { __asm__ volatile ("hlt"); }
    }

    // 2. Ensure framebuffer is initialized
    if (framebuffer_request.response == NULL || framebuffer_request.response->framebuffer_count < 1) {
        while (1) { __asm__ volatile ("hlt"); }
    }

    fb = framebuffer_request.response->framebuffers[0];

    // 3. Clear display buffer (Dark Slate background: 0x001A1C23)
    clear_screen(0x001A1C23);

    // 4. Load Descriptor Tables
    gdt_init();
    idt_init();

    // 5. Initialize and launch shell prompt
    shell_init();

    // 6. Enter shell event loop
    while (1) {
        shell_run();
    }
}
