[package]
name = "shacmp"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "hashcmp"
path = "src/main.rs"
 
[dependencies]
sha2 = "0.11"
hex = "0.4"
clap = { version = "4.6", features = ["derive"] }
walkdir = "2.5"
notify = "8.2"
eframe = "0.34"
egui = "0.34"
 
[profile.release]
opt-level = 3
strip = true
